In [3]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
zeo=np.zeros(10)

In [5]:
zeo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
one=np.ones(5)

In [ ]:
l_space=np.linspace(1,20,6)

print(l

NameError: name 'l' is not defined

In [ ]:
n=5
for i in range (n):
    spaces= " " * i
    stars= "*" * ( n-i)
    print(spaces+stars)




*****
 ****
  ***
   **
    *
